function getData(){

    
    var items = [//Para crear un item
        
        new primitives.orgdiagram.ItemConfig({
            id: 0,
            parent: null,
            hasSelectorCheckbox: false,
            title: "Presidencia",                       
            templateName: "CursorTemplate",
            itemTitleColor: "#559E4A",
            students:5          
        }),
        
        new primitives.orgdiagram.ItemConfig({ 
            id: 1, 
            parent: 0, 
            hasSelectorCheckbox: false,
            title: "Hernando Peña",
            description: "VP, Human Resources",
            image: "./img/photos/skull.jpg",
            groupTitle: "Presidente",
            groupTitleColor: "#559E4A",
            itemTitleColor: "#559E4A",            
            email: "vadaduho@name.com", 
            phone: "303-333-9215" ,
            contract: "Indefinido",
            antiquity: 15,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 54,
            civilStatus: "soltero",
            workingStatus: "Incapacitado",
            dateStart: "2014-06-19",
            dateEnd: "2015-06-19" , 
            competences: ["Conocimientos en excel.","Lectura y escritura en inglés.","Habilidades en narración oral y escrita Habilidades en narración oral y escrita. "],     
            percentage: [75, 35, 50],
            dependence: "Presidencia",
            disciplinaryProcesses: [], 
            curses: ["Cocina"," Asistencia Administrativa"],
            charge: "Presidente",
        }),
        //Para crear un item principal
        new primitives.orgdiagram.ItemConfig({ 
            id: 2, 
            parent: 1, 
            hasSelectorCheckbox: true,
            templateName: "CursorTemplate", 
            title: "Gerencia", 
            itemTitleColor: "#F94141",
            students:5,
            
        }),
        new primitives.orgdiagram.ItemConfig({ 
            id: 3,
            parent: 1,
            hasSelectorCheckbox: false,
            templateName: "CursorTemplate", 
            title: "Recursos Humanos", 
            itemTitleColor: "#3B5FD1",
            students:8,
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 4, 
            parent: 1,
            hasSelectorCheckbox: false,
            templateName: "CursorTemplate",
            title: "Finanzas",
            itemTitleColor: "#54BAB5",
            students:13,
        }),
        
        new primitives.orgdiagram.ItemConfig({ 
            id: 5, 
            parent: 1,
            hasSelectorCheckbox: false,
            templateName: "CursorTemplate",
            title: "Compras",
            itemTitleColor: "#d13784",
            students:10,
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 6, 
            parent: 2, 
            isVisible: true, 
            description: "GM, Core Operating System Test", 
            email: "vadaduho@name.com", 
            groupTitleColor: "#F94141", 
            image: "./img/photos/woman.jpg", 
            itemTitleColor: "#F94141", 
            phone: "303-333-9215", 
            title: "Diana Montoya", 
            groupTitle: "Gerente", 
            contract: "Indefinido",
            antiquity: 8,
            salary: 800000,          
            address: "Calle 3 # 12- 34",
            age: 42,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Conocimientos en excel","Lectura y escritura en inglés","Actitud de lider"], 
            percentage: [15, 75, 50],            
            dependence: "Gerencia",
            disciplinaryProcesses: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus."],
            curses: [],
            charge: "Gerente",
        }),
               
        new primitives.orgdiagram.ItemConfig({
            id: 7,
            parent: 6,
            title: "Daniel Castro",
            description: "VP, Human Resources",
            image: "./img/photos/man.jpg",
            itemTitleColor: "#F94141",
            groupTitle: "Subgerente",
            groupTitleColor: "#F94141",            
            email: "vadaduho@name.com", 
            phone: "303-333-9215",
            contract: "Indefinido",
            antiquity: 6,
            salary: 1300000,          
            address: "Calle 3 # 12- 34",
            age: 24,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,  
            competences: ["Conocimientos en excel","Lectura y escritura en inglés"], 
            percentage: [85, 55],
            dependence: "Gerencia",
            disciplinaryProcesses: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus."],
            curses: ["Cocina"," Asistencia Administrativa"],
            charge: "Subgerente",
        }),

        new primitives.orgdiagram.ItemConfig({
            id: 8,
            parent: 3,
            title: "Andrés Solano",
            description: "VP, Human Resources",
            image: "./img/photos/man.jpg",
            itemTitleColor: "#3B5FD1",
            groupTitle: "Psicólogo",
            groupTitleColor: "#3B5FD1",            
            email: "vadaduho@name.com", 
            phone: "303-333-9215", 
            contract: "Indefinido",
            antiquity: 3,
            salary: 1240000,          
            address: "Calle 3 # 12- 34",
            age: 24,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Conocimientos en excel","Lectura y escritura en inglés"], 
            percentage: [85, 55],
            dependence: "Recursos Humanos",
            disciplinaryProcesses: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus."],
            curses: [],
            charge: "Psicólogo",

        }),
       
        new primitives.orgdiagram.ItemConfig({ 
            id: 9, 
            parent: 8, 
            isVisible: true, 
            description: "VP & CFO, NAME", 
            email: "barblang@name.com", 
            groupTitleColor: "#3B5FD1", 
            image: "./img/photos/woman.jpg", 
            itemTitleColor: "#3B5FD1", 
            phone: "318-822-7345", 
            title: "Barbara Perez" ,
            groupTitle: "Asistente", 
            contract: "Indefinido",
            antiquity: 15,
            salary: 2600000,          
            address: "Calle 3 # 12- 34",
            age: 35,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Facilidad para hablar","Lectura y escritura en inglés"], 
            percentage: [35, 65],
            dependence: "Recursos Humanos", 
            disciplinaryProcesses: [],
            curses: ["Cocina"," Asistencia Administrativa"], 
            charge: "Asistente",
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 10, 
            parent: 8, 
            isVisible: true, 
            description: "VP, NAME Operations", 
            email: "barbfaul@name.com", 
            groupTitleColor: "#3B5FD1", 
            image: "./img/photos/woman.jpg", 
            itemTitleColor: "#3B5FD1", 
            phone: "641-678-7646", 
            title: "Barbara Montes" , 
            groupTitle: "Psicóloga",
            contract: "Indefinido",
            antiquity: 4,
            salary: 980000,          
            address: "Calle 3 # 12- 34",
            age: 42,
            civilStatus: "soltero",
            workingStatus: "Embarazada",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Altos conocimientos en datos financieros","Lectura y escritura en inglés"],   
            percentage: [85, 55],
            dependence: "Recursos Humanos",
            disciplinaryProcesses: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus."],
            curses: ["Cocina"," Asistencia Administrativa"],
            charge: "Psicóloga"
        }),

        new primitives.orgdiagram.ItemConfig({
            id: 11,
            parent: 3,
            title: "Carlos Durango",
            description: "VP, Human Resources",
            image: "./img/photos/man.jpg",
            itemTitleColor: "#3B5FD1",
            groupTitle: "Asistente",
            groupTitleColor: "#3B5FD1",
            email: "barbfaul@name.com", 
            phone: "641-678-7646",
            contract: "Indefinido",
            antiquity: 3,
            salary: 1000000,          
            address: "Calle 3 # 12- 34",
            age: 32,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Conocimientos básicos en archivo","Lectura y escritura en inglés"], 
            percentage: [28, 36],
            dependence: "Recursos Humanos",
            disciplinaryProcesses: [],
            curses: ["Cocina"," Asistencia Administrativa"],
            charge: "Asistente",   
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 12, 
            parent: 11, 
            isVisible: true, 
            description: "VP, NAME Global Sales & Marketing", 
            email: "stewwill@name.com", 
            groupTitleColor: "#3B5FD1", 
            image: "./img/photos/man.jpg", 
            itemTitleColor: "#3B5FD1", 
            phone: "803-746-8733", 
            title: "Stewart Williams" , 
            groupTitle: "Presidente", 
            contract: "Indefinido",
            antiquity: 2,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 21,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Escritura con buena ortografía","Lectura y escritura en inglés"], 
            percentage: [85, 55],
            dependence: "Recursos Humanos",
            disciplinaryProcesses: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus."],
            curses: [],
            charge: "Presidente",
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 13, 
            parent: 11, 
            isVisible: true, 
            description: "Sr. VP, NAME Information Services & Merchant Platform", 
            email: "robelemi@name.com", 
            groupTitleColor: "#3B5FD1", 
            image: "./img/photos/man.jpg", 
            itemTitleColor: "#3B5FD1", 
            phone: "425-590-4308", 
            title: "Robert Lemieux" , 
            groupTitle: "Co-Presidente", 
            contract: "Indefinido",
            antiquity: 2,
            salary: 1300000,          
            address: "Calle 3 # 12- 34",
            age: 24,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Escritura con buena ortografía","Lectura y escritura en inglés"], 
            percentage: [85, 55],
            dependence: "Recursos Humanos",
            disciplinaryProcesses: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus."],
            curses: ["Cocina"," Asistencia Administrativa"],
            charge: "Co-Presidente"
        }),

        new primitives.orgdiagram.ItemConfig({
            id: 14,
            parent: 4   ,
            title: "Alfredo Bonilla",
            description: "VP, Human Resources",
            image: "./img/photos/man.jpg",
            email: "robelemi@name.com",
            phone: "425-590-4308", 
            itemTitleColor: "#54BAB5",
            groupTitle: "Administrador",
            groupTitleColor: "#54BAB5",
            contract: "Indefinido",
            antiquity: 1,
            salary: 1400000,          
            address: "Calle 3 # 12- 34",
            age: 31,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Conocimientos básicos en archivo","Lectura y escritura en inglés"], 
            percentage: [75, 35],
            dependence: "Finanzas",
            disciplinaryProcesses: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus."],
            curses: ["Cocina"," Asistencia Administrativa"],
            charge: "Administrador"
        }),

        new primitives.orgdiagram.ItemConfig({
            id: 15,
            parent: 14,
            title: "Ted Whitt 2",
            description: "VP,Kaaaa",
            hasSelectorCheckbox: false,
            image: "./img/photos/man.jpg",
            itemTitleColor: "#54BAB5",
            groupTitleColor: "#54BAB5",
            groupTitle: "Asis. Comercial", 
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 10,
            salary: 1100000,          
            address: "Calle 3 # 12- 34",
            age: 36,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Conocimientos básicos en archivo","Lectura y escritura en inglés"], 
            percentage: [85, 59],
            dependence: "Finanzas",
            disciplinaryProcesses: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus."],
            curses: [],
            charge: "Asis. Comercial",
        }),

        new primitives.orgdiagram.ItemConfig({
            id: 16, 
            parent: 5, 
            isVisible: true, 
            description: "VP, Security Technology Unit (STU)", 
            title: "Catalina Rendón",
            email: "robemorg@name.com1", 
            groupTitleColor: "#d13784", 
            image: "./img/photos/woman.jpg", 
            itemTitleColor: "#d13784",
            groupTitle: "Compradora", 
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 6,
            salary: 1200000,          
            address: "Calle 3 # 12- 34",
            age: 26,
            civilStatus: "soltero",
            workingStatus: "Licencia Materna",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Altos conocimientos en datos financieros","Lectura y escritura en inglés"],  
            percentage: [75, 35],
            dependence: "Compras",
            disciplinaryProcesses: [],
            curses: [],
            charge: "Compradora"
        }),
        
        new primitives.orgdiagram.ItemConfig({ 
            id: 17, 
            parent: 14, 
            isVisible: true, 
            description: "VP, NAME Communications Services and Member Platform", 
            title: "Juan Perez",
            groupTitleColor: "#54BAB5", 
            image: "./img/photos/man.jpg",
            itemTitleColor: "#54BAB5", 
            groupTitle: "Director",
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 7,
            salary: 1600000,          
            address: "Calle 3 # 12- 34",
            age: 23,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Altos conocimientos en datos financieros","Lectura y escritura en inglés"], 
            percentage: [84, 95],
            dependence: "Finanzas", 
            disciplinaryProcesses: [],
            curses: ["Cocina"," Asistencia Administrativa"],
            charge: "Director"   
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 18, 
            parent: 14, 
            isVisible: true, 
            description: "VP & CFO, NAME",            
            groupTitleColor: "#54BAB5", 
            image: "./img/photos/woman.jpg", 
            itemTitleColor: "#54BAB5", 
            title: "Barbara Lang" , 
            groupTitle: "Asistente",
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 5,
            salary: 1900000,          
            address: "Calle 3 # 12- 34",
            age: 22,
            civilStatus: "soltero",
            workingStatus: "Licencia Materna",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Conocimientos en excel","Lectura y escritura en inglés","Actitud de lider"], 
            percentage: [25, 46, 95],
            dependence: "Finanzas",
            disciplinaryProcesses: [],
            curses: [],
            charge: "Asistente",
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 19, 
            parent: 14, 
            isVisible: true, 
            description: "VP, NAME Operations", 
            groupTitleColor: "#54BAB5", 
            image: "./img/photos/woman.jpg", 
            itemTitleColor: "#54BAB5", 
            title: "Barbara Faulk" , 
            groupTitle: "Secretaria",
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 4,
            salary: 970000,          
            address: "Calle 3 # 12- 34",
            age: 19,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Conocimientos en excel","Lectura y escritura en inglés","Actitud de lider"], 
            percentage: [55, 75, 23],
            dependence: "Finanzas",
            disciplinaryProcesses: [],
            curses: ["Cocina"," Asistencia Administrativa"],
            charge: "Secretaria",
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 20, 
            parent: 14, 
            isVisible: true, 
            description: "VP, NAME Global Sales & Marketing", 
            groupTitleColor: "#54BAB5", 
            image: "./img/photos/man.jpg", 
            itemTitleColor: "#54BAB5", 
            title: "Stewart Williams" , 
            groupTitle: "Contador",
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 3,
            salary: 1400000,          
            address: "Calle 3 # 12- 34",
            age: 35,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Facilidad para hablar","Lectura y escritura en inglés"], 
            percentage: [75, 35],
            dependence: "Finanzas",
            disciplinaryProcesses: [],
            curses: [],
            charge: "Contador",
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 21, 
            parent: 15, 
            isVisible: true, 
            description: "VP, NAME Global Sales & Marketing", 
            groupTitleColor: "#54BAB5", 
            image: "./img/photos/man.jpg", 
            itemTitleColor: "#54BAB5", 
            title: "Stewart Williams" , 
            groupTitle: "Secretario", 
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 10,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 41,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Facilidad para hablar","Lectura y escritura en inglés"], 
            percentage: [75, 35],
            dependence: "Finanzas",
            disciplinaryProcesses: [],
            curses: ["Cocina"," Asistencia Administrativa"],
            charge: "Secretario",
        }),
        new primitives.orgdiagram.ItemConfig({ 
            id: 22, 
            parent: 21,
            hasSelectorCheckbox: false,
            templateName: "CursorTemplate",
            title: "Tesorería",
            itemTitleColor: "#d51f26",
            students:9,  
        }),        
        new primitives.orgdiagram.ItemConfig({ 
            id: 24, 
            parent: 22, 
            isVisible: true, 
            description: "VP, NAME Global Sales & Marketing", 
            groupTitleColor: "#d51f26", 
            image: "./img/photos/man.jpg", 
            itemTitleColor: "#d51f26", 
            title: "Cristian Lopez" , 
            groupTitle: "Tesorero", 
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 10,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 41,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Facilidad para hablar","Lectura y escritura en inglés"], 
            percentage: [75, 35],
            dependence: "Tesorería",
            disciplinaryProcesses: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus."],
            curses: ["Cocina"," Asistencia Administrativa"],
            charge: "Tesorero",
        }),
        new primitives.orgdiagram.ItemConfig({ 
            id: 25, 
            parent: 12, 
            isVisible: true, 
            description: "VP, NAME Global Sales & Marketing", 
            email: "stewwill@name.com", 
            groupTitleColor: "#3B5FD1", 
            image: "./img/photos/man.jpg", 
            itemTitleColor: "#3B5FD1", 
            phone: "803-746-8733", 
            title: "Cristian Lopez" , 
            groupTitle: "Secretario", 
            contract: "Indefinido",
            antiquity: 2,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 21,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Escritura con buena ortografía","Lectura y escritura en inglés"], 
            percentage: [85, 55],
            dependence: "Recursos Humanos",
            disciplinaryProcesses: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus."],
            curses: [],
            charge: "Secretario"
        }),  
        new primitives.orgdiagram.ItemConfig({ 
            id: 26, 
            parent: 9, 
            isVisible: true, 
            description: "VP & CFO, NAME", 
            email: "barblang@name.com", 
            groupTitleColor: "#3B5FD1", 
            image: "./img/photos/woman.jpg", 
            itemTitleColor: "#3B5FD1", 
            phone: "318-822-7345", 
            title: "Katherine Perez" ,
            groupTitle: "Secretaria", 
            contract: "Indefinido",
            antiquity: 15,
            salary: 2600000,          
            address: "Calle 3 # 12- 34",
            age: 35,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Facilidad para hablar","Lectura y escritura en inglés"], 
            percentage: [35, 65],
            dependence: "Recursos Humanos", 
            disciplinaryProcesses: [],
            curses: ["Cocina"," Asistencia Administrativa"], 
            charge: "Secretaria",
        }),
        new primitives.orgdiagram.ItemConfig({ 
            id: 27, 
            parent: 26, 
            isVisible: true, 
            description: "VP & CFO, NAME", 
            email: "barblang@name.com", 
            groupTitleColor: "#3B5FD1", 
            image: "./img/photos/man.jpg", 
            itemTitleColor: "#3B5FD1", 
            phone: "318-822-7345", 
            title: "Roberto Medrano" ,
            groupTitle: "Conciliador", 
            contract: "Indefinido",
            antiquity: 15,
            salary: 2600000,          
            address: "Calle 3 # 12- 34",
            age: 35,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Facilidad para hablar","Lectura y escritura en inglés"], 
            percentage: [35, 65],
            dependence: "Recursos Humanos", 
            disciplinaryProcesses: [],
            curses: ["Cocina"," Asistencia Administrativa"], 
            charge: "Conciliador",
        }),
    ];

    return items;

}
function getDataBlob(){

    
    var items = [//Para crear un item
        
        new primitives.orgdiagram.ItemConfig({
            id: 0,
            parent: null,
            hasSelectorCheckbox: false,
            title: "Presidencia",
            itemTitleColor: "#555555",           
            templateName: "DepartmentTitleTemplate",
            itemTitleColor: "#559E4A" 
        }),
        
        new primitives.orgdiagram.ItemConfig({ 
            id: 1, 
            parent: 0, 
            hasSelectorCheckbox: false,
            title: "Fritz Stüger",
            description: "VP, Human Resources",
            image: photos.b,
            groupTitle: "Institucional",
            // templateName: "CursorTemplate",
            groupTitleColor: "#559E4A",
            itemTitleColor: "#559E4A",            
            email: "vadaduho@name.com", 
            phone: "303-333-9215" ,
            contract: "Indefinido",
            antiquity: 15,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 54,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Conocimientos en excel.","Lectura y escritura en inglés.","Habilidades en narración oral y escrita Habilidades en narración oral y escrita Habilidades en narración oral y escrita Habilidades en narración oral y escrita Habilidades en narración oral y escrita. "],      
        }),
        //Para crear un item principal
        new primitives.orgdiagram.ItemConfig({ 
            id: 2, 
            parent: 1, 
            hasSelectorCheckbox: true,
            templateName: "DepartmentTitleTemplate", 
            title: "Gerencia", 
            itemTitleColor: "#F94141",
            
        }),
        new primitives.orgdiagram.ItemConfig({ 
            id: 3,
            parent: 1,
            hasSelectorCheckbox: false,
            templateName: "DepartmentTitleTemplate", 
            title: "Recursos Humanos", 
            itemTitleColor: "#3B5FD1" 
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 4, 
            parent: 1,
            hasSelectorCheckbox: false,
            templateName: "DepartmentTitleTemplate",
            title: "Financiera",
            itemTitleColor: "#54BAB5"
        }),
        
        new primitives.orgdiagram.ItemConfig({ 
            id: 5, 
            parent: 1,
            hasSelectorCheckbox: false,
            templateName: "DepartmentTitleTemplate",
            title: "Admnistrativa",
            itemTitleColor: "#d13784",
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 6, 
            parent: 2, 
            isVisible: true, 
            description: "GM, Core Operating System Test", 
            email: "vadaduho@name.com", 
            groupTitleColor: "#F94141", 
            image: photos.v, 
            itemTitleColor: "#F94141", 
            phone: "303-333-9215", 
            title: "Vada Duhon", 
            groupTitle: "Presidente", 
            contract: "Indefinido",
            antiquity: 15,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 42,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Conocimientos en excel","Lectura y escritura en inglés","Actitud de lider"], 
            
        }),
               
        new primitives.orgdiagram.ItemConfig({
            id: 7,
            parent: 2,
            title: "Ted Whitt 2",
            description: "VP, Human Resources",
            image: photos.t,
            itemTitleColor: "#F94141",
            groupTitle: "Mecánico",
            groupTitleColor: "#F94141",            
            email: "vadaduho@name.com", 
            phone: "303-333-9215",
            contract: "Indefinido",
            antiquity: 15,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 24,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,  
            competences: ["Conocimientos en excel","Lectura y escritura en inglés"], 
        }),

        new primitives.orgdiagram.ItemConfig({
            id: 8,
            parent: 3,
            title: "Ted Whitt 2",
            description: "VP, Human Resources",
            image: photos.t,
            itemTitleColor: "#3B5FD1",
            groupTitle: "Mecánico",
            groupTitleColor: "#3B5FD1",            
            email: "vadaduho@name.com", 
            phone: "303-333-9215", 
            contract: "Indefinido",
            antiquity: 15,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 24,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Conocimientos en excel","Lectura y escritura en inglés"], 
        }),
       
        new primitives.orgdiagram.ItemConfig({ 
            id: 9, 
            parent: 8, 
            isVisible: true, 
            description: "VP & CFO, NAME", 
            email: "barblang@name.com", 
            groupTitleColor: "#3B5FD1", 
            image: photos.b, 
            itemTitleColor: "#3B5FD1", 
            phone: "618-822-7345", 
            title: "Barbara Lang" ,
            groupTitle: "Presidente", 
            contract: "Indefinido",
            antiquity: 15,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 35,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Facilidad para hablar","Lectura y escritura en inglés"], 
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 10, 
            parent: 8, 
            isVisible: true, 
            description: "VP, NAME Operations", 
            email: "barbfaul@name.com", 
            groupTitleColor: "#3B5FD1", 
            image: photos.v, 
            itemTitleColor: "#3B5FD1", 
            phone: "641-678-7646", 
            title: "Barbara Faulk" , 
            groupTitle: "Presidente",
            contract: "Indefinido",
            antiquity: 25,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 42,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Altos conocimientos en datos financieros","Lectura y escritura en inglés"],   
        }),

        new primitives.orgdiagram.ItemConfig({
            id: 11,
            parent: 3,
            title: "Andrea Wild",
            description: "VP, Human Resources",
            image: photos.a,
            itemTitleColor: "#3B5FD1",
            groupTitle: "Mecánico",
            groupTitleColor: "#3B5FD1",
            email: "barbfaul@name.com", 
            phone: "641-678-7646",
            contract: "Indefinido",
            antiquity: 15,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 32,
            civilStatus: "soltero",
            workingStatus: "Licencia Materna",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Conocimientos básicos en archivo","Lectura y escritura en inglés"], 
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 12, 
            parent: 11, 
            isVisible: true, 
            description: "VP, NAME Global Sales & Marketing", 
            email: "stewwill@name.com", 
            groupTitleColor: "#3B5FD1", 
            image: photos.s, 
            itemTitleColor: "#3B5FD1", 
            phone: "803-746-8733", 
            title: "Stewart Williams" , 
            groupTitle: "Presidente", 
            contract: "Indefinido",
            antiquity: 15,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 21,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Escritura con buena ortografía","Lectura y escritura en inglés"], 
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 13, 
            parent: 11, 
            isVisible: true, 
            description: "Sr. VP, NAME Information Services & Merchant Platform", 
            email: "robelemi@name.com", 
            groupTitleColor: "#3B5FD1", 
            image: photos.r, 
            itemTitleColor: "#3B5FD1", 
            phone: "425-590-4308", 
            title: "Robert Lemieux" , 
            groupTitle: "Presidente", 
            contract: "Indefinido",
            antiquity: 15,
            salary: 900000,          
            address: "Calle 3 # 12- 34",
            age: 24,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Escritura con buena ortografía","Lectura y escritura en inglés"], 
        }),

        new primitives.orgdiagram.ItemConfig({
            id: 14,
            parent: 4   ,
            title: "Ted Whitt 2",
            description: "VP, Human Resources",
            image: photos.t,
            email: "robelemi@name.com",
            phone: "425-590-4308", 
            itemTitleColor: "#54BAB5",
            groupTitle: "Mecánico",
            groupTitleColor: "#54BAB5",
            contract: "Indefinido",
            antiquity: 15,
            salary: 2300000,          
            address: "Calle 3 # 12- 34",
            age: 31,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" , 
            competences: ["Conocimientos básicos en archivo","Lectura y escritura en inglés"], 
        }),

        new primitives.orgdiagram.ItemConfig({
            id: 15,
            parent: 14,
            title: "Ted Whitt 2",
            description: "VP,Kaaaa",
            hasSelectorCheckbox: false,
            image: photos.g,
            itemTitleColor: "#54BAB5",
            groupTitleColor: "#54BAB5",
            groupTitle: "Presidente", 
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 1,
            salary: 950000,          
            address: "Calle 3 # 12- 34",
            age: 36,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Conocimientos básicos en archivo","Lectura y escritura en inglés"], 

        }),

        new primitives.orgdiagram.ItemConfig({
            id: 16, 
            parent: 5, 
            isVisible: true, 
            description: "VP, Security Technology Unit (STU)", 
            title: "Catalina Rendón",
            email: "robemorg@name.com1", 
            groupTitleColor: "#d13784", 
            image: photos.c, 
            itemTitleColor: "#d13784",
            groupTitle: "Presidente", 
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 2,
            salary: 1100000,          
            address: "Calle 3 # 12- 34",
            age: 26,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Altos conocimientos en datos financieros","Lectura y escritura en inglés"],  
        }),
        
        new primitives.orgdiagram.ItemConfig({ 
            id: 17, 
            parent: 14, 
            isVisible: true, 
            description: "VP, NAME Communications Services and Member Platform", 
            title: "Juan Perez",
            groupTitleColor: "#54BAB5", 
            image: photos.j,
            itemTitleColor: "#54BAB5", 
            groupTitle: "Presidente",
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 4,
            salary: 4200000,          
            address: "Calle 3 # 12- 34",
            age: 23,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Altos conocimientos en datos financieros","Lectura y escritura en inglés"],           
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 18, 
            parent: 14, 
            isVisible: true, 
            description: "VP & CFO, NAME",            
            groupTitleColor: "#54BAB5", 
            image: photos.o, 
            itemTitleColor: "#54BAB5", 
            title: "Barbara Lang" , 
            groupTitle: "Presidente",
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 3,
            salary: 1600000,          
            address: "Calle 3 # 12- 34",
            age: 22,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Conocimientos en excel","Lectura y escritura en inglés","Actitud de lider"], 
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 19, 
            parent: 14, 
            isVisible: true, 
            description: "VP, NAME Operations", 
            groupTitleColor: "#54BAB5", 
            image: photos.b, 
            itemTitleColor: "#54BAB5", 
            title: "Barbara Faulk" , 
            groupTitle: "Presidente",
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 15,
            salary: 1300000,          
            address: "Calle 3 # 12- 34",
            age: 19,
            civilStatus: "soltero",
            workingStatus: "Trabaja",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Conocimientos en excel","Lectura y escritura en inglés","Actitud de lider"], 
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 20, 
            parent: 14, 
            isVisible: true, 
            description: "VP, NAME Global Sales & Marketing", 
            groupTitleColor: "#54BAB5", 
            image: photos.s, 
            itemTitleColor: "#54BAB5", 
            title: "Stewart Williams" , 
            groupTitle: "Presidente",
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 6,
            salary: 1500000,          
            address: "Calle 3 # 12- 34",
            age: 35,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Facilidad para hablar","Lectura y escritura en inglés"], 
        }),

        new primitives.orgdiagram.ItemConfig({ 
            id: 21, 
            parent: 15, 
            isVisible: true, 
            description: "VP, NAME Global Sales & Marketing", 
            groupTitleColor: "#54BAB5", 
            image: photos.z, 
            itemTitleColor: "#54BAB5", 
            title: "Stewart Williams" , 
            groupTitle: "Presidente", 
            email: "robelemi@name.com",
            phone: "425-590-4308",
            contract: "Indefinido",
            antiquity: 2,
            salary: 2500000,          
            address: "Calle 3 # 12- 34",
            age: 41,
            civilStatus: "soltero",
            workingStatus: "Vacaciones",
            dateStart: "Junio 22 2018 ",
            dateEnd: "Julio 9 2018" ,
            competences: ["Facilidad para hablar","Lectura y escritura en inglés"], 
        })
        
    ];

    return items;

}
